### PR TITLE
feat: completed team page

### PR DESCRIPTION
**Pull request by Ehidiamhen**
I have completed the 'Our Team' page of the website

### CODE REVIEW

**Comment by LeRoiCodes** [comment]
are you available for some work?

**Review by LeRoiCodes — APPROVED** [review]
great

**Comment by Ehidiamhen** [comment]
On what exactly

**Comment by LeRoiCodes** [comment]
everything

**Comment by LeRoiCodes** [comment]
or can you do the landing page
seems like if we wait for micheal we might not have anything

**Comment by LeRoiCodes** [comment]
ok but I need that page

**Pull request merged**
